pkg/ipam/address/address.go, pkg/ipam/address/api.go, pkg/vsphere/provisioning/nictype/api.go, pkg/vsphere/provisioning/nictype/nic_type.go, pkg/vsphere/provisioning/vm/definition.go, tests/ipam_test.go, tests/nic_type_test.go
Add nic type endpoint
```release-note
Add nic type endpoint
```
=> add nic type endpoint

.github/pull_request_template.md, Makefile, pkg/vsphere/provisioning/vm/definition.go, tests/vsphere_test.go
Fix tests and pull_request_template
```release-note
None
```
=> Fix tests and pull_request_template

pkg/core/location/api.go, pkg/core/location/location.go, tests/core_test.go
improve core location endpoint
```release-note
None
```
=> improve core location endpoint

pkg/core/tags/api.go, pkg/core/tags/tags.go, tests/core_test.go
add missing params to tags list function
```release-note
add missing params to tags list function
```
=> add additional params to tags list function

pkg/core/tags/tags.go, pkg/vsphere/provisioning/location/api.go, pkg/vsphere/provisioning/location/list.go, tests/vsphere_test.go
Fix Vsphere Locations Endpoint
```release-note
Fix Vsphere Locations Endpoint
```
=> Fix Vsphere Locations Endpoint

pkg/ipam/address/address.go, pkg/vlan/vlan.go, pkg/vsphere/info/info.go
```release-note
Add missing fields for import
```
=> add mising fields

CHANGELOG.md
Add Changelog for release 0.3.19
=> Release version 0.3.19

CHANGELOG.md
Adde changelog for the release 0.3.21
=> Added changelog for v0.3.21

pkg/vsphere/api.go, pkg/vsphere/vmlist/api.go, pkg/vsphere/vmlist/vmlist.go, tests/vsphere_test.go
This PR adds the `vmlist` API to the SDK.
```release-note
- vmlist API added to SDK
```
=> Add vmlist API

CHANGELOG.md
Prepare `CHANGELOG.md` for `v0.3.23`
=> Prepare changelog.md for v0.3.23

pkg/lbaas/acl/acl.go, pkg/lbaas/acl/api.go, pkg/lbaas/acl/definition.go, pkg/lbaas/lbaas.go, tests/lbaas_test.go
* add ACL API to LBaaS API
```release-note
* lbaas - add ACL API
```
=> Add ACL API to LBaaS API

CHANGELOG.md
prepare changelog for new release
=> prepare-changelog-for-0.3.25

CHANGELOG.md
Prepare Changelog.md for version 0.3.27
=> Prepare Changelog for version 0.3.27

CHANGELOG.md
=> Update CHANGELOG.md for version 0.3.28

pkg/core/location/api.go, pkg/core/location/location.go, tests/core_test.go
This adds wrapper routines for the core/location/`<identifier>` and core/location/by-code/`<code>`
```release-note
ENHANCEMENTS
* core/location - Add getters for locations by identifier and code
```
=> ✨: Implement endpoints to get locations by identifier and code

tests/vsphere_test.go
They currently fail because of engine problems, to allow developing here, we disable them for now.
```release-note
NONE
```
=> Make vsphere tests pending

.github/pull_request_template.md
Add a format description to the PR template.
```release-note
NONE
```
=> add a format description to PR template

README.md
Adds some docs for the generic client to README, also adds deprecation notice and hides example for legacy clients in a spoiler.
```release-note
NONE (doc change)
```
* generic client introduced in #56 
* deprecating old clients as decided in meeting ([meeting notes](https://ais.anexia-it.com/pages/viewpage.action?pageId=101135855))
=> 📝: add generic client example to README

CHANGELOG.md
Prepare release v0.4.1 by adding the version to CHANGELOG.md
=> prepare release v0.4.1

CHANGELOG.md, pkg/apis/lbaas/v1/backend_types.go, pkg/apis/lbaas/v1/bind_types.go, pkg/apis/lbaas/v1/frontend_types.go, pkg/apis/lbaas/v1/loadbalancer_types.go, pkg/apis/lbaas/v1/server_types.go, pkg/apis/lbaas/v1/state.go, pkg/apis/lbaas/v1/types.go
Add easy getters for LBaaS resource state
* (to-be-opened CCM PR)
* replaces some of the code in https://github.com/anexia-it/anxcloud-cloud-controller-manager/pull/44
=> 🎨 lbaas/v1: unify state attribute and add getters

pkg/utils/object/filter/filter.go, pkg/utils/object/filter/filter_example_test.go, pkg/utils/object/filter/filter_test.go, pkg/utils/object/filter/types.go
=> Add object filter helper

pkg/api/api_implementation.go, pkg/api/api_test.go, pkg/api/pagination_test.go, pkg/api/reexport.go, pkg/api/types/context.go, pkg/api/types/object_test.go, pkg/client/client.go, pkg/client/metrics.go, pkg/utils/object/compare/compare.go, pkg/utils/object/filter/filter.go, pkg/utils/test/hostname.go, pkg/utils/test/name.go
There is quite some warnings `go lint` throws at us, this PR fixes some of them.
=> Fixing some linting errors

CHANGELOG.md, pkg/apis/core/v1/resource_tags.go
=> Added helper functions for tagging and untagging of resources

CHANGELOG.md
Prepare release v0.4.4, so we can release a fixed CCM
=> Prepare release v0.4.4

CHANGELOG.md
=> Prepare release v0.4.5

CHANGELOG.md, pkg/api/api.go, pkg/api/api_implementation.go, pkg/api/e2e_test.go, pkg/api/errors.go, pkg/api/internal/options.go, pkg/api/mock/mock_api_implementation.go, pkg/api/options.go, pkg/api/options_example_test.go, pkg/api/types/operation.go, pkg/api/types/types.go, pkg/apis/core/v1/helper/tag.go, pkg/apis/core/v1/resource_tags.go, pkg/apis/core/v1/resource_test.go
=> Implement AutoTag option for api.Create

CHANGELOG.md
=> Prepare release v0.4.6

pkg/apis/kubernetes/v1/cluster_test.go, pkg/apis/kubernetes/v1/crud_test.go, pkg/apis/kubernetes/v1/integration_test.go, pkg/apis/kubernetes/v1/mock_handlers_test.go
AwaitCompletion tests have been moved back to `crud_test.go` to fix integration tests.
=> Enable and fix integration tests

CHANGELOG.md, pkg/apis/kubernetes/v1/crud_test.go, pkg/apis/kubernetes/v1/kubeconfig_genclient.go, pkg/apis/kubernetes/v1/kubeconfig_helper.go, pkg/apis/kubernetes/v1/kubeconfig_test.go, pkg/apis/kubernetes/v1/mock_handlers_test.go, pkg/apis/kubernetes/v1/xxgenerated_object.go
Add helper functions to handle kubeconfig operations.
Based on #151 
=> Add helper functions to handle kubeconfig operations

CHANGELOG.md
=> Prepare release v0.5.1

.github/workflows/integration.yml, CHANGELOG.md, pkg/api/e2e_test.go, pkg/apis/kubernetes/v1/kubeconfig_helper.go, pkg/ipam/address/integration_test.go, pkg/ipam/prefix/integration_test.go, pkg/vsphere/integration_test.go, pkg/vsphere/provisioning/ips/integration_test.go
=> Partially fix integration tests and rework v0.5.1 release

go.mod, go.sum, tools/go.mod, tools/go.sum
Combination of #245, #246 and #247 for integration test efficiency.
=> Combined update of logr, gomega and golangci-lint

.github/workflows/code.yml, CHANGELOG.md
=> Add changelog

.github/dependabot.yml
Add @eiabea and myself to dependabot assignees.
=> Add dependabot assignees

CHANGELOG.md, pkg/vsphere/provisioning/vm/definition.go
=> ANXKUBE-308: allow provisioning of additional vm disks

CHANGELOG.md
=> Prepare release v0.5.3

CHANGELOG.md, pkg/utils/object/filter/filter.go, pkg/utils/object/filter/filter_example_test.go, pkg/utils/object/filter/filter_test.go
=> Support common.PartialResource in filter helper

CHANGELOG.md
Prepare changelog for v0.6.1 release.
=> Prepare release v0.6.1

CHANGELOG.md
Prepare changelog for v0.6.2 release.
=> Prepare release v0.6.2

.github/workflows/update-go.anx.io.yml
Don't merge before the go.anx.io repo isn't moved.
=> Update the location of go.anx.io

.github/workflows/code.yml
Add missing "include everything" to the trigger paths of the code workflow before adding excludes.
=> Fix code workflow trigger paths

pkg/ipam/address/integration_test.go, pkg/ipam/prefix/integration_test.go, pkg/vsphere/integration_test.go, pkg/vsphere/provisioning/ips/integration_test.go
Change integration tests to use some other fixed resources
=> Change integration tests to use some other fixed resources

CHANGELOG.md
Prepare CHANGELOG for release.
=> Prepare v0.6.3 release

CHANGELOG.md
=> Release v0.7.3

CHANGELOG.md
=> Prepare release `0.7.4`

CHANGELOG.md
=> chore: release 0.7.5

CHANGELOG.md
New patch release of go-anxcloud
=> SYSENG-1820: prepare release 0.7.7

CHANGELOG.md, README.md, pkg/vsphere/integration_test.go, pkg/vsphere/provisioning/vm/definition.go
=> Replace all occurrences of vmxnet3 with virtio

pkg/core/location/location.go, pkg/ipam/address/address.go, pkg/ipam/prefix/prefix.go, pkg/vlan/vlan.go
Increase Security in the search parameter.
no user facing change
=> Escape search query parameters API
