anexia-it/go-anxcloud

pkg/vlan/api.go
pkg/vlan/vlan.go
tests/vlan_test.go

add 'search' param to vlan endpoint
```release-note
None
```

add 'search' param to vlan endpoint

---

pkg/vsphere/provisioning/cpuperformancetypes/api.go
pkg/vsphere/provisioning/cpuperformancetypes/cpu_performance_types.go
tests/vsphere_test.go

add list cpu performance types api
```release-note
add list cpu performance types api
```

add list cpu performance types api

---

pkg/vsphere/provisioning/vm/api.go
pkg/vsphere/provisioning/vm/provision.go
tests/vsphere_test.go

add option to pass base64 encrypted script
```release-note
Add option to encrypt script by base64
```

add option to pass base64 encrypted script

---

pkg/ipam/prefix/prefix.go

add missing fields for network prefix
```release-note
None
```

add missing fields for network prefix

---

pkg/core/location/location.go
pkg/core/resource/resource.go
pkg/core/service/service.go
pkg/core/tags/tags.go
pkg/ipam/address/address.go
pkg/ipam/prefix/prefix.go
pkg/test/echo/echo.go
pkg/vlan/vlan.go
pkg/vsphere/info/info.go
pkg/vsphere/powercontrol/powercontrol.go
pkg/vsphere/provisioning/cpuperformancetypes/cpu_performance_types.go
pkg/vsphere/provisioning/disktype/disktype.go
pkg/vsphere/provisioning/ips/ips.go
pkg/vsphere/provisioning/location/list.go
pkg/vsphere/provisioning/nictype/nic_type.go
pkg/vsphere/provisioning/progress/progress.go
pkg/vsphere/provisioning/templates/templates.go
pkg/vsphere/provisioning/vm/api.go
pkg/vsphere/provisioning/vm/deprovision.go
pkg/vsphere/provisioning/vm/provision.go
pkg/vsphere/provisioning/vm/update.go
pkg/vsphere/search/name.go
tests/vsphere_test.go

Added explicit handling for 500 error codes. Avoid trying to decode json.
```release-note
Added explicit handling for 500 error codes. Avoid trying to decode json.
```

5xx handling

---

pkg/ipam/prefix/prefix.go
tests/ipam_test.go

Update network prefix Info response model to reflect the changes on API side. To get the vlan ID `vlans` should be used, containing a list of VLANs.
Updated ipam/prefix Info model for list of VLANs on response.
```release-note
```

Network prefix api update

---

CHANGELOG.md
pkg/vsphere/info/info.go
tests/e2e_suite_test.go

Changed `location_id` to `location_identifier` to reflect the anxcloud API virtual server info response.
```release-note
BUGFIXES
* Changed location identifier tag name
```

Changed location id tag name for info model

---

pkg/vsphere/info/info.go
tests/e2e_suite_test.go
tests/vsphere_test.go

Disk sizes should be floating point values to support all values received from engine.
```release-note
*  Changed disk size attribute to floating point value
```

Disk float support

---

pkg/vlan/vlan.go
tests/vlan_test.go

Added the `vm_provisioning` flag to the VLAN update structure.
```release-note
* vlan - added `vm_provisioning` flag to `UpdateDefinition`
```

vm_provisioning Flag for VLAN update

---

pkg/ipam/address/address.go

Add random sleep delay to `ReserveRandom` API to work-a-round a race-condition when reserving IPs on the same VLAN concurrently.
```release-note
* ipam/address - random sleep added to ip reservation as workaround
```

Added random sleep to IP reservation client

---

pkg/vsphere/info/info.go
tests/vsphere_test.go

Changed the disk size variable from float32 to float64 as this should be the native size and provides some additional performance boost.

Changed float32 to float64 on disk size

---

CHANGELOG.md

Update Changelog for version 0.3.20
```release-note
BUGFIXES
* vsphere/info - `DiskGB` variable type changed from float32 to float64
```

Updated Changelog for v0.3.20

---

.github/workflows/code.yml
CHANGELOG.md
go.mod
go.sum
pkg/client/client.go
pkg/client/client_test.go
pkg/client/test.go
pkg/client/token.go
pkg/client/token_test.go

Ths PR adds logging capabilities to the client implementation. When configured, it writes both request and response to the configured `io.Writer`. 
```release-note
* client/option: Added `io.Writer` to log request and response
```

Provide request/response logging capabilities

---

CHANGELOG.md

Added changelog for release 0.3.22
```release-note
* clouddns - Added CloudDNS API
```

Added changelog for release 0.3.22

---

CHANGELOG.md
pkg/vsphere/provisioning/progress/progress.go
tests/vsphere_test.go

The removed empty case didn't do anything. Go has no automatic fall through in cases. This code was looped until there was a timeout of the context
```release-note
Fix a bug where 404 from progress API results in a loop until timeout
```

Fix a bug where 404 from progress API results in a loop until timeout

---

Makefile
pkg/client/client.go
pkg/client/token.go
pkg/client/useragent_test.go
tools/main.go

Allow to specify a user agent during a client creation
```release-note
ENHANCEMENTS
client - Add client option to provide a user agent
```

Allow to specify a user agent

---

pkg/vsphere/provisioning/vm/api.go
pkg/vsphere/provisioning/vm/deprovision.go
tests/vsphere_test.go

The Deprovision endpoint returns an progress identifier, which allows to use the existing `AwaitCompletion` function to block until the VM disappears. 
PS. Tests is adjusted to await the deletion now
```release-note
* vsphere - Deprovision now returns progress identifier
```

Return Progress Identifier on Deprovision API Call

---

pkg/ipam/prefix/prefix.go
tests/ipam_test.go

Return type of the prefix
```release-note
* ipam/prefix - return type from API 
```

Add Prefix type to prefix info 

---

pkg/ipam/address/address.go
pkg/ipam/address/api.go
pkg/ipam/prefix/prefix.go
pkg/utils/param/param.go
pkg/vsphere/provisioning/templates/templates.go
tests/ipam_test.go
tests/param_test.go

The Anexia API allows to to create an empty prefix when the given flag is specified.
also added the GetFiltered method for address retrieval and a general purpos packag for query parameter building
```release-note
* ipam/prefix - allow to create empty prefixes
* ipam/address - allow to retrieve addresses with given filters
```

Allow to create empty prefixes

---

pkg/api/api.go
pkg/api/api_examples_test.go
pkg/api/api_implementation.go
pkg/api/api_test.go
pkg/api/doc.go
pkg/api/errors.go
pkg/api/errors_test.go
pkg/api/internal/options.go
pkg/api/mockserver_test.go
pkg/api/object.go
pkg/api/object_example_test.go
pkg/api/options.go
pkg/api/pagination.go
pkg/api/pagination_test.go
pkg/api/reexport.go
pkg/api/types/object.go
pkg/api/types/operation.go
pkg/api/types/options.go
pkg/api/types/options_test.go
pkg/api/types/pagination.go
pkg/api/types/types.go
pkg/lbaas/backend/api.go
pkg/lbaas/backend/backend.go
pkg/lbaas/frontend/api.go
pkg/lbaas/loadbalancer/api.go
pkg/lbaas/loadbalancer/loadbalancer.go

This PR adds a new generic API client only requiring a handful lines of code on an API resource to be compatible to it. It's inspired by the kubernetes client, but not completely following it.
Many people reviewing this would be appreciated, while it seems to work with the already implemented API resources, I'm not sure if it's generic enough for all our APIs.
Feedback on the usage interface of this new client is also appreciated, I have uploaded the docs for this branch to the webserver to my [home router](https://karl.lf-net.org/go-anxcloud/pkg/github.com/anexia-it/go-anxcloud/pkg/api/) (it's a `wget -nH -m $godoc_server` and some nginx redirects).
```release-note
* adding a new generic API …
```

New generic API client for less code duplication

---

pkg/client/client.go
pkg/client/error.go

Extracting ResponseError and the logic to parse it into error.go to
reduce complexity in client.go.
```release-note
NONE
```

🎨: extract client error handling in new file

---

pkg/client/client.go
pkg/client/metrics.go
pkg/client/metrics_test.go

Add interface to retrieve metrics from client, specifically request (inflight) counters and duration. Can be used for prometheus metrics in CCM or timing info in terraform provider for example.
```release-note
* add new feature to retrieve metrics from client
```
SYSENG-526

SYSENG-526 ✨: add interface to get client metrics

---

pkg/api/api_test.go
pkg/api/object.go
pkg/api/object_test.go
pkg/api/types/object.go

This PR adds support for "github.com/satori/go.uuid".UUID Object identifiers in generic client.
```release-note
NONE (updates non-releases functionality)
```
Generic client introduced in #56

Allow UUID identifiers in generic client

---

pkg/api/errors.go
pkg/api/object.go
pkg/api/object_test.go

This extends `getObjectIdentifier` to recursively search for identifier field in embedded/anonymous fields, too.
```release-note
NONE (addition to unreleased feature)
```
Generic client introduced in #56

✨: allow Object identifiers in embedded fields

---

pkg/api/api_examples_test.go
pkg/api/api_implementation.go
pkg/api/api_test.go
pkg/api/mockserver_test.go
pkg/api/pagination.go
pkg/api/pagination_test.go

CurrentPage() is expected to return the page currently retrieved, which page the data in the passed array belongs to. Update test to reflect that.
currentPage was incremented before doing the API request, meaning it returned the page last tried to be retrieved instead of the last one retrieved successfully. Now currentPage+1 is requested and currentPage is incremented on success.
Add check for query argument page != 0 in pagination test.
Also fixes a bad data race when listing objects using a channel.
```release-note
NONE (fixes for unreleased code)
```
Introduced in #56
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues …

pagination fixes in generic client

---

tests/e2e_suite_test.go
tests/vsphere_test.go

Previously there was a template ID hardcoded in the tests, we now have a Name hardcoded and list all templates, selecting one that matches the name (always using the lexically highest build-string).
```release-note
NONE (tests updated)
```
The CI runs failed today.

✅💚: vsphere: search good template for tests

---

pkg/api/api_implementation.go
pkg/api/api_test.go
pkg/api/pagination.go
pkg/api/pagination_test.go
pkg/api/types/object.go

Some API endpoints do not support pagination, ignoring the query argument and just returning all data all the time - making the pageIter and objectchannel return all data in an endless loop over and over again.
This hook allows objects to configure if they support paginated list operations, even dynamically if they support only when some filters are (not) set or something.
```release-note
NONE (part of generic client which isn't released yet)
```
Needs fixes from #68 
* If …

Allow objects to disable paginated List operations

---

pkg/api/api_implementation.go
pkg/api/api_test.go
pkg/api/context.go
pkg/api/context_test.go
pkg/api/errors.go
pkg/api/pagination.go
pkg/api/types/object.go

This adds the ResponseDecodeHook as discussed in SYSENG-686.
Using this hook, an Object can have completely custom decoding, matching the already existing `RequestBodyHook`. The Object is required to decode the data in the given `io.Reader` into the receiver, storing the decoded data into itself.
To implement this with non-redundant code, the logic to decode an Object is exported into it's own function, used by all parts of the generic client (`api_implementation.go/doRequest()`, `api_implementation.go/List()/channel goroutine function` and `pagination.go/Next()`).
While implementing this new hook, we realized many arguments passed to the hook functions are actually kind of "the context". Because of this, we extended the context used by the generic client to include the `Operation`, …

SYSENG-686 ✨: Introduce ResponseDecodeHook for manipulating returned objects

---

pkg/api/api_implementation.go
pkg/api/api_test.go

This PR allows the generic client to handle empty/missing response bodies.
```release-note
NONE (fix for unreleased generic client)
```

Generic client: handle empty response bodies

---

pkg/api/api.go
pkg/api/api_examples_test.go

Many API endpoints for listing resources only return a subset of data of a single object. This PR adds documentation in the two examples for listing (via PageInfo and via Channel) and on `API.List()`.
```release-note
* NONE (doc update for unreleased feature)
```
* generic client introduced in #56 

📝: document List operations returning incomplete data

---

tests/vsphere_test.go

VSphere integration tests were disabled in #76. They seem to work again, let's run them again.
```release-note
NONE
```
* disabled in #76 

Re-enable vsphere integration tests

---

pkg/test/echo/echo_test.go

The test had another package than the one it is testing, resulting in multiple packages being defined in a single directory. This commit fixes that.
```release-note
NONE
```

🎨: change test package name of pkg/test/echo

---

pkg/api/api_examples_test.go
pkg/api/api_implementation.go
pkg/api/api_test.go
pkg/api/internal/options.go
pkg/api/options.go
pkg/api/types/types.go

List operations with results via channel had to be read until everything was received. This PR implements the ability to cancel the context, cancelling the List operation.
Also renames the `AsObjectChannel` option to `ObjectChannel`, looks better imho.
```release-note
* NONE (addition to unreleased feature)
```
* generic client introduced in #56 
* Closes #81 (this is a better way to do that)
* If you are interested in working on this issue or have submitted a pull …

Allow cancelling List operations via channel

---

pkg/api/api_examples_test.go
pkg/api/mockserver_test.go
pkg/apis/core/v1/resource_genclient.go
pkg/apis/core/v1/resource_types.go
pkg/apis/core/v1/spec_runner_test.go
pkg/apis/core/v1/xxgenerated_object_test.go
pkg/apis/lbaas/v1/backend_genclient.go
pkg/apis/lbaas/v1/backend_types.go
pkg/apis/lbaas/v1/frontend_genclient.go
pkg/apis/lbaas/v1/frontend_types.go
pkg/apis/lbaas/v1/loadbalancer_genclient.go
pkg/apis/lbaas/v1/loadbalancer_types.go
pkg/apis/lbaas/v1/spec_runner_test.go
pkg/apis/lbaas/v1/types.go
pkg/apis/lbaas/v1/xxgenerated_object_test.go
pkg/core/resource/api.go
pkg/core/resource/resource.go
pkg/lbaas/backend/api.go
pkg/lbaas/backend/backend.go
pkg/lbaas/common/common.go
pkg/lbaas/frontend/api.go
pkg/lbaas/frontend/frontend.go
pkg/lbaas/loadbalancer/api.go
pkg/lbaas/loadbalancer/loadbalancer.go

This makes much more visible which APIs are supported by the generic client, makes it easier to have generic client supporting APIs not sharing any code with existing old clients and is a place where other big projects place their API definitions.
```release-note
* NONE (unreleased feature)
```
* for generic client introduced in #56 
* moves core/resources API built in #67 
* If you are interested in working on this issue or have submitted a pull request, please leave a …

Move generic client APIs into pkg/apis/

---

pkg/apis/lbaas/v1/loadbalancer_types.go

Currently we have `DisallowUnknownFields` enabled in the generic client, which requires us to have all API response fields in our Go types. This adds the state attribute to the lbaasv1.LoadBalancer type.
```release-note
* add State attribute to Loadbalancer type
```

👽️: add State member to lbaas/LoadBalancer

---

go.mod
go.sum
pkg/api/api.go
pkg/api/api_examples_test.go
pkg/api/api_implementation.go
pkg/api/api_test.go
pkg/api/internal/options.go
pkg/api/mockserver_test.go
pkg/api/options.go
pkg/api/pagination.go
pkg/api/pagination_test.go
pkg/api/types/operation.go

I think title says enough already ^^'
This also fixes some other small things, neatly in their own commits.
```release-note
* NONE (updating unreleased code)
```
* generic client introduced in #56
* SYSENG-684

Add `FullObjects` option, retrieving full objects on listing

---

tests/vsphere_test.go

For proper version sorting we need to extract the number from the `build` property of a template. The `build` Property is currently not enforcing any format however there is at least some kind of convention that I tried to put in a regex.
```release-note
None 
```

Fix template build sorting in tests

---

tests/vsphere_test.go

When discovering the latest template, the wrong capture group was used, since the first match always contains the whole match.
Also added tests so that something like this doesn't happen again if the regex needs to be changed in the future
```release-note
NONE
```

use correct capture group index

---

.github/workflows/code.yml
.github/workflows/dependency.yml
.github/workflows/documentation.yml
.github/workflows/integration.yml
.github/workflows/unit.yml
docs/go-versions.md
go.mod

This changes the minimum Go version of this package to 1.16, the minimal currently supported version of Go, and adds documentation how we are going to lift the minimum Go version required by this package.
Also changes the GitHub actions workflows to matrix-test two Go versions, currently 1.16 and 1.17.
```release-note
* now requiring at least Go 1.16
```

Upgrade to go 1.16 and document target version

---

README.md

The current example in the go code might lead users to not paying attention to pointers inside the API objects and causing race conditions when the objects are contentiously used after the loop, this can be eliminated by re-initializing  the object on every loop cycle. 
```release-note
NONE
```

Improve go code example in Readme.md

---

pkg/apis/lbaas/v1/backend_types.go
pkg/apis/lbaas/v1/frontend_genclient.go
pkg/apis/lbaas/v1/frontend_types.go
pkg/apis/lbaas/v1/loadbalancer_types.go
pkg/apis/lbaas/v1/types.go

This fixes some problems in the generic client code for LBaaS:
* Frontend wasn't a valid object (missing `anxcloud:"identifier"` tag)
* Backend and Frontend have State and AutomationRules, too
Also adds support for filtering Frontends on LoadBalancer and mode and slightly improves docs.
```release-note
NONE (update to unreleased feature)
```
* problems where found while doing #90 
* generic client introduced in #56
* LBaaS support for generic client was built as first test case there
* we need these fields added due to problem described in [SYSENG-753 (internal only)](https://ats.anexia-it.com/browse/SYSENG-753)
* Please vote on this issue by adding a 👍 …

Some LBaaS generic client fixes

---

.github/pull_request_template.md
CHANGELOG.md
CONTRIBUTING.md
LICENSE
README.md
SECURITY.md
docs/code-generator.md

This restructures the contribution/dev-workflow docs and adds/reformats documents we have in our OpenSource repository template.
When reviewing this, best look at it commit for commit to have a much better overview what is changing.
```release-note
NONE
```
* [SYSENG-682](https://ats.anexia-it.com/browse/SYSENG-682)

Restructure and reformat docs

---

pkg/api/api_implementation.go
pkg/api/api_test.go
pkg/api/object_example_test.go
pkg/api/pagination_test.go
pkg/apis/clouddns/v1/xxgenerated_object_test.go
pkg/apis/clouddns/v1/zone_genclient.go
pkg/apis/clouddns/v1/zone_types.go

We configured the JSON decoder in use by the generic client to
`DisallowUnknownFields` before, because encoding/json does not know
about required fields, resulting in every json object being decodable
into every Go struct, but we want to make sure the response is actually
the type we expect.
Turns out this is only really needed for checking which style of
pagination response we got, not for objects and we already have
different code paths for decoding pagination responses and objects. This
commit allows unknown fields for objects.
We previously had a test case for a valid pagination response with
invalid objects in it. We did not see that in real life (as far as we
remember), so we removed that test case - hoping the Engine does not
throw such responses at us.
* …

✅🩹: allow unknown fields in most responses

---

pkg/vsphere/integration_test.go

Template name changed in the Engine from `Flatcar Linux Stable` to `Flatcar Linux stable` ... use prefix `Flatcar Linux` instead.
Technically the `stable`/`Stable` is the version field of the template, just not differentiated via API - so with this change we select the highest `build` of the `Flatcar Linux` template, regardless of its version.
* [SYSENG-866](https://ats.anexia-it.com/browse/SYSENG-866)

vsphere integration tests: template name prefix

---

.github/workflows/update-go.anx.io.yml

The go.anx.io update workflow was only called for branches, this changes it to also trigger on pushed tags.

CI: update go.anx.io on pushed tags

---

CHANGELOG.md
pkg/api/types/errors.go
pkg/apis/core/v1/location_e2e_test.go
pkg/apis/core/v1/location_genclient.go
pkg/apis/core/v1/location_test.go
pkg/apis/core/v1/location_types.go
pkg/apis/core/v1/xxgenerated_object_test.go
pkg/apis/vlan/v1/genclient.go
pkg/apis/vlan/v1/types.go
pkg/apis/vlan/v1/vlan_e2e_mock_test.go
pkg/apis/vlan/v1/vlan_e2e_prod_test.go
pkg/apis/vlan/v1/vlan_e2e_test.go
pkg/apis/vlan/v1/vlan_test.go
pkg/apis/vlan/v1/xxgenerated_object_test.go
pkg/utils/test/object.go

This adds generic client support for the VLAN API. Also adds `corev1.Location`, as VLAN needs it.

Add VLAN bindings for generic client

---

CHANGELOG.md
go.mod
go.sum
pkg/api/object.go
pkg/api/object_test.go
pkg/apis/clouddns/v1/mocks_test.go
pkg/clouddns/zone/mocks_test.go

That library seems dead and we have to replace it, which would be a breaking change as it's part of the public interface of the old CloudDNS client.
For now, upgrading to latest master version fixes a security issue.
This PR also removes all usages not part of a public interface, so removing the whole dependency will be possible when the (already deprecated) old CloudDNS client is gone.
* with SYSENG-1023 I planned to replace the UUID package, but after this PR merged and the already deprecated old clients removed, we can remove the dependency instead of replacing it …

⬆️🔥: upgrade gh/satori/go.uuid and remove usages of it where possible

---

CHANGELOG.md
pkg/apis/core/v1/resource_e2e_test.go
pkg/apis/core/v1/resource_genclient.go
pkg/apis/core/v1/resource_test.go
pkg/apis/core/v1/resource_types.go
pkg/apis/core/v1/xxgenerated_object_test.go
pkg/core/resource/resource.go

No one knew why it was named Info in the first place, Resource fits better as the API calles it that, too.
Also adds the Attributes field to corev1.Resource as json.RawMessage to decode into an Object without an extra call to the API.
* introduced in #67, I missed the name while reviewing

💥✨: rename corev1.Info to corev1.Resource

---

pkg/apis/core/v1/resource_genclient.go
pkg/apis/core/v1/resource_test.go
pkg/apis/core/v1/resource_types.go
pkg/apis/core/v1/xxgenerated_object_test.go
pkg/utils/test/object.go

This adds support for tagging objects via generic client.
Also fixes a bug with retrieving objects via core/v1.Resource - tags were not decoded correctly.
* bad decoding introduced in #67 
* SYSENG-1152

Tag objects with generic client

---

CHANGELOG.md
pkg/api/api_implementation.go
pkg/api/errors.go
pkg/api/errors_test.go

Exporting ErrorFromResponse() and (the new) NewHTTPError() simplifies
mocking a lot and makes mocking a generic client possible.
Again needed for CCM but also just good to have.

Export some pkg/api.HTTPError things

---

CHANGELOG.md
pkg/apis/clouddns/v1/mocks_test.go
pkg/apis/clouddns/v1/record_genclient.go
pkg/apis/clouddns/v1/zone_test.go

Generic client bindings for CloudDNS didn't use the response body for Record Create and Update requests, making it hard to get the identifier of a newly created Record.
* [SYSENG-1187](https://ats.anexia-it.com/browse/SYSENG-1187)

🐛: fill Identifier for CDNS Record via genclient

---

.github/workflows/integration.yml
.github/workflows/update-go.anx.io.yml

This PR disables (trusted, still possible via ok-to-test) integration tests and go.anx.io updates for dependabot branches/PRs.
It is needed as dependabot has it's own collection of secrets and I don't want to duplicate them for it. Unit tests should be enough, we can still trigger integration tests with slash command if needed and we certainly don't need dependabot branches in go.anx.io

dependabot: no integration tests and go.anx.io update

---

pkg/apis/clouddns/v1/record_genclient.go

Fix `ErrModifyRecordNotFound` error message in generic clouddns/v1 API

fix clouddns ErrModifyRecordNotFound error message revision->record

---

CHANGELOG.md
pkg/apis/lbaas/v1/backend_genclient.go
pkg/apis/lbaas/v1/backend_types.go
pkg/apis/lbaas/v1/bind_genclient.go
pkg/apis/lbaas/v1/bind_types.go
pkg/apis/lbaas/v1/frontend_genclient.go
pkg/apis/lbaas/v1/frontend_types.go
pkg/apis/lbaas/v1/helper.go
pkg/apis/lbaas/v1/loadbalancer_genclient.go
pkg/apis/lbaas/v1/loadbalancer_types.go
pkg/apis/lbaas/v1/server_genclient.go
pkg/apis/lbaas/v1/server_types.go
pkg/apis/lbaas/v1/state.go
pkg/apis/lbaas/v1/xxgenerated_object_test.go

When creating a Backend, only a certain subset of attributes was sent to the Engine.
Also improves the request body handling for all the LBaaS objects, unifying Create and Update and omitting the State attribute instead of choosing the correct one to send and adds some `omitempty` tags to Object fields.
* [SYSENG-1230](https://ats.anexia-it.com/browse/SYSENG-1230)

SYSENG-1230: fix missing LBaaS Backend attributes for Create operations

---

CHANGELOG.md

This updates the changelog for release 0.4.3, to be released today.
Also updates the changelog format comment, giving some fresh examples and making clear the entries are to be added below that comment - so I'll don't have to move the entries below it anymore when preparing a release.

Prepare release 0.4.3

---

CHANGELOG.md
pkg/utils/object/compare/reconcile.go
pkg/utils/object/compare/reconcile_test.go

Allow passing arrays of pointers or Objects as target/existing array to pkg/utils/object/compare.Reconcile and add the test case for this.
Quite some more changes to make CodeClimate happy again.
* needed for https://github.com/anexia-it/k8s-anexia-ccm/pull/91

compare.Reconcile: fix passing ptr arrays

---

pkg/apis/lbaas/v1/acl_genclient.go
pkg/apis/lbaas/v1/acl_test.go
pkg/apis/lbaas/v1/acl_types.go
pkg/apis/lbaas/v1/e2e_connection_test.go
pkg/apis/lbaas/v1/e2e_test.go
pkg/apis/lbaas/v1/example_test.go
pkg/apis/lbaas/v1/rule_genclient.go
pkg/apis/lbaas/v1/rule_test.go
pkg/apis/lbaas/v1/rule_types.go
pkg/apis/lbaas/v1/xxgenerated_object_test.go
pkg/utils/pointer/convert.go
pkg/utils/pointer/convert_test.go

Add missing LBaaS ACL and rule bindings

---

CHANGELOG.md
pkg/apis/vsphere/v1/main_test.go
pkg/apis/vsphere/v1/template_genclient.go
pkg/apis/vsphere/v1/template_helpers.go
pkg/apis/vsphere/v1/template_test.go
pkg/apis/vsphere/v1/template_types.go
pkg/apis/vsphere/v1/xxgenerated_object_test.go

Add generic vSphere Template bindings and FindNamedTemplate helper to mitigate deleted VM template (ENGSUP-5913) issues.

Add generic vSphere Template bindings and FindNamedTemplate helper

---

pkg/apis/lbaas/v1/e2e_connection_test.go

Fix LBaaS connectionResetByPeerCheck e2e helper by expecting it to `Eventually` `Succeed`.
#142 introduced this helper.

Fix LBaaS connectionResetByPeerCheck e2e helper

---

CHANGELOG.md
pkg/apis/clouddns/v1/mocks_test.go
pkg/apis/clouddns/v1/record_genclient.go
pkg/apis/clouddns/v1/record_types.go
pkg/apis/clouddns/v1/xxgenerated_object_test.go
pkg/apis/clouddns/v1/zone_test.go
pkg/clouddns/zone/mocks_test.go
pkg/clouddns/zone/record.go
pkg/clouddns/zone/zone_test.go

Due to changes of a default value in the CloudDNS API (record name) we decided to disallow the creation of DNS records with an empty name parameter. Use `"@"` as name instead to target the root domain.

Disallow creation of DNS records with empty names

---

.github/workflows/integration.yml

Our integration tests often fail due to changes in other systems, making them a bad tool to recognize if a PR is safe to merge. To reduce unnecessary load on our systems, we disable integration tests for pull request - due to the fact in the first sentence, we don't look at the "Failed" result anyway.
We should definitely revise this in the future, enabling some integration tests matching the changes in the PR (e.g. re-run `pkg/apis/lbaas/v1` integration tests when something was changed below that).
* If you are interested in working on this issue or have submitted a …

disable integration tests for pull requests

---

CHANGELOG.md
pkg/client/log_utils.go

Client trace logging (requests and responses) was broken, logging only the pointer to the request/response body instead of the contents. This PR fixes that.

pkg/client: fix trace logging request/response bodies

---

CHANGELOG.md
pkg/client/client.go

Instead of sending all trace logs to one logger configured on the client, we instead send it to the logr.Logger attached to the request context and fallback to the client logger.

pkg/client: trace log to logger attached to request context

---

CHANGELOG.md
pkg/apis/common/gs/resource.go
pkg/apis/common/gs/resource_test.go
pkg/apis/common/resource.go
pkg/apis/common/resource_test.go
pkg/apis/kubernetes/v1/cluster_genclient.go
pkg/apis/kubernetes/v1/cluster_test.go
pkg/apis/kubernetes/v1/cluster_types.go

This PR adds fields to the Kubernetes cluster API resource which allow configurable prefixes. It also adds common resource types to work with generic services.

Extend Kubernetes Cluster bindings to include prefixes

---

Makefile
tools/.gitignore
tools/go.mod
tools/go.sum
tools/tools.go

Finally not every ginkgo update twice via dependabot!
See changelog of ginkgo v2.8.2, which allowed running ginkgo like that: https://github.com/onsi/ginkgo/releases/tag/v2.8.2

ginkgo: remove from tools and run with version in go.mod

---

pkg/api/e2e_test.go
pkg/apis/clouddns/v1/main_test.go
pkg/apis/clouddns/v1/mocks_test.go
pkg/apis/clouddns/v1/zone_test.go
pkg/apis/lbaas/v1/e2e_test.go
pkg/clouddns/zone/main_test.go
pkg/clouddns/zone/mocks_test.go
pkg/clouddns/zone/zone_test.go
pkg/vsphere/vsphere_test.go

When changing `RandomHostname` and `TestResourceName` in #227, I only ran the unit tests... of course that change broke quite some integration tests, this PR fixes them.
It's some more rework in the CloudDNS test suites, should run faster now as we don't create a fresh zone for each single test anymore.

Fix most integration tests after #227 broke them

---

.github/workflows/code.yml
.github/workflows/dependency.yml
.github/workflows/documentation.yml
CHANGELOG.md
go.mod
tools/go.mod

Upgrading to Go 1.20, while also testing with Go 1.21.
Needed for #291

Upgrade to Go 1.20

---

CHANGELOG.md
pkg/apis/kubernetes/v1/crud_test.go
pkg/apis/kubernetes/v1/example_test.go
pkg/apis/kubernetes/v1/node_pool_types.go

Prepare changelog for v0.6.0 release

Prepare release v0.6.0

---

CHANGELOG.md
pkg/api/mock/hooks.go
pkg/api/mock/mock_api_implementation.go

Adds "pre-create" hook functionality to the mock API client.

Add hooks to mock API client

---

CHANGELOG.md
pkg/apis/e5e/v1/function_types.go
pkg/apis/e5e/v1/suite_test.go

Rename e5e storage backend 'zip' to 'archive' and add the new `deployment_state` attribute.

SYSENG-1658: Update e5e function types

---

.github/workflows/code.yml
CHANGELOG.md
pkg/api/api_implementation.go
pkg/api/api_test.go
pkg/api/internal/options.go
pkg/api/mock/mock_api_implementation.go
pkg/api/object_example_test.go
pkg/api/options.go
pkg/api/types/options.go
pkg/apis/kubernetes/v1/cluster_genclient.go
pkg/apis/kubernetes/v1/common.go
pkg/apis/kubernetes/v1/crud_test.go
pkg/apis/kubernetes/v1/node_pool_genclient.go
pkg/vsphere/integration_test.go

This PR adds functionality to define default requests options via `WithRequestOptions` when creating a new generic API client.

SYSENG-1357: generic client default options

---

CHANGELOG.md
pkg/apis/kubernetes/v1/cluster_types.go

This PR adds the `autoscaling` property to the Kubernetes cluster object, which is already present in the current Engine release.

SYSENG-1764: Add autoscaling to clusters

---

CHANGELOG.md

Prepare v0.7.0 release

---

CHANGELOG.md
pkg/ipam/address/address.go
pkg/ipam/prefix/prefix.go

Add ip-version and prefix filter attributes to `ReserveRandom` request

---

.gitignore
CHANGELOG.md
pkg/api/api_implementation.go
pkg/api/api_test.go
pkg/client/client.go

If `WithLogger` was not called yet, we're now using the underlying logger of the client then.
Closes SYSENG-1746.

SYSENG-1746: Use logger of underlying client

---

CHANGELOG.md
pkg/api/mock/hooks.go
pkg/api/mock/mock_api_implementation.go
pkg/api/mock/mock_api_implementation_test.go

This adds a pre-update hook in addition to the pre-create hook.

Add pre-update hook

---

CHANGELOG.md
pkg/vsphere/provisioning/vm/definition.go

According to the api documentation it is possible to set the bandwidth limit. With this change it is possible to do the same with the go client.

add possibility to set bandwidth limit for vms

---

CHANGELOG.md
pkg/vsphere/provisioning/progress/progress.go
pkg/vsphere/provisioning/progress/progress_test.go

Make the `status` field of provisioning progress accessible.

fix: make status field accessible

---

CHANGELOG.md
pkg/vsphere/provisioning/progress/progress.go
pkg/vsphere/provisioning/progress/progress_test.go

A mistake slipped through review and tests: progress.Status returned by the API is a string.

fix: progress.Status is a string

---

CHANGELOG.md
pkg/vsphere/info/info.go

This was missed in the first PR to add the ability to set `bandwidth_limit` as the info endpoint is required to have this field as well, for the Terraform provider to work.

SYSENG-1806: Add missing `bandwidth_limit` field in `info.Network` stuct

---

CHANGELOG.md
pkg/apis/clouddns/v1/mocks_test.go
pkg/apis/clouddns/v1/zone_genclient.go
pkg/clouddns/zone/zone.go

Consistently use zone_name in Anexia Engine requests, fixes integration test failures.

ENGSUP-8949: consistently use zone_name instead of zoneName.

---

CHANGELOG.md
pkg/api/errors.go
pkg/api/errors_test.go

Rate limits got introduced by the Anexia Engine at some point in the second half of 2024. Most of our integrations were not prepared for this, especially CCM is suffering from this.
In order to detect rate limits sent by the Engine, a new RateLimitError was added, together with a timestamp after which the requests should be retried again.
I decided to introduce a complex type with a placeholder value for this timestamp right now. This allows us to build other integrations on top of it and when we later update the timestamp with the correct value of the Retry-After header (ENGSUP-9027), all existing implementations would benefit from that without any further manual changes.
Related: ANXKUBE-1281
* Please vote on this issue by adding a 👍 …

Add dedicated RateLimitError for HTTP code 429

---

CHANGELOG.md
pkg/ipam/prefix/api.go
pkg/ipam/prefix/integration_test.go
pkg/ipam/prefix/prefix.go

Adds search option to the prefix api.

add search to the prefix api

---

CHANGELOG.md
pkg/api/errors.go
pkg/api/errors_test.go

It does not fix the mentioned issue, but at least our newer client errors are now compatible with the errors.Is method.
Related: SYSENG-1804

Add errors.Is handling for HTTPError
